// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ornaiobdjbogiuwajndo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ybmFpb2JkamJvZ2l1d2FqbmRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NTI1MTUsImV4cCI6MjA2ODEyODUxNX0.CqjGlnGsz9dZgng8v30xcvicv-C64aBV9zgdPX9tfRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});